version: "3.7"

services:
  docker-nginx:
    depends_on:
      - docker-php
    image: nginx
    container_name: docker-nginx
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    networks:
      normal:
        aliases:
          - docker-nginx
    volumes:
      - './www:/var/www/html'
      - './nginx:/etc/nginx'

  docker-mysql:
    image: mysql:8.0.28
    container_name: docker-mysql
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: test
    volumes:
      - './mysql/data:/var/lib/mysql'
    ports:
      - "3307:3306"
    networks:
      normal:
        aliases:
          - docker-mysql

  docker-redis:
    image: redis
    container_name: docker-redis
    expose:
      - 6379
    restart: always
    volumes:
#        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
        - ./redis/data:/data:rw
    ports:
      - "6380:6379"
    networks:
      normal:
        aliases:
          - docker-redis

  docker-php:
    depends_on:
      - docker-mysql
    container_name: docker-php
    build: ./php/.
    restart: always
    volumes:
      - './www:/var/www/html'
    networks:
      normal:
        aliases:
          - master
#    command:
#      - /bin/sh
#      - -c
#      - |
#        python3 *.py
networks:
  normal:
    driver: bridge